### ISSUE TITLE
Fix console error: error de análisis XML: no se encontraron elementos

### ISSUE THREAD

**Issue by topcatarg** [g3rv4/Traducir#99]
Sorry I don't have exactly the translated text. 

This is an easy fix. Blank results or empty results returned on net.core controllers give this error. To fix this, we should change the blank results to OkObjectResult(null); 

This is what you see on the navigator console:

![captura](https://user-images.githubusercontent.com/14790006/45836053-2689dc80-bce2-11e8-80c0-f9ca1cf17c73.PNG)

**Comment by g3rv4** [comment]
Here's the error in English:

![message](https://user-images.githubusercontent.com/6250774/45841412-1ed13480-bcf0-11e8-8a48-f699cb6d289e.png)

Now, what's interesting is that the server ISN'T returning a content type that's XML

![headers](https://user-images.githubusercontent.com/6250774/45841424-2a246000-bcf0-11e8-9021-c9d119ec0416.png)

According to [this answer on Stack Overflow](https://stackoverflow.com/a/46487392/920295), it's a bug with Firefox. I totally agree... since nothing is telling Firefox to parse the response as an XML.

I wouldn't use `OkObjectResult`... I would return an empty response that ends up returning the status code 204 (No Content). I would expect Firefox to avoid parsing it as an XML then?

**Comment by topcatarg** [comment]
[This answer in SO](https://stackoverflow.com/a/37690852/73749) has the rigth option.

We should return NoContent() if we need a 204 status code.
